---
hostname: "admin-machine"
kubectl_version: "v1.31.3"
kube_version: "v1.31.3"
cri_tools_version: "v1.31.1"
runc_version: "v1.2.2"
cni_plugins_version: "v1.6.2"
containerd_version: "v2.0.0"
etcd_version: "v3.5.17"
# vars for certs
ca_dir: "/tmp/ca"   #Path on local machine to store certs momentarily after generation
certs_dir: "/tmp/certs" #Path on local machine to store certs momentarily after generation
conf_dir: "/tmp/conf" #Path on local machine to generate ca.conf file
ca_key: "{{ ca_dir }}/ca.key"  
ca_cert: "{{ ca_dir }}/ca.crt"
ca_conf: "{{ ca_dir }}/ca.conf"
common_conf: "{{ ca_dir }}/common.conf"
domain: "myrrhsolutions.co.in"   #If you have a domain for which you want certs to be generated as well
kubelet_path: "/var/lib/kubelet"
ansible_user: "ansible"   #any other user under which you are running ansible playbooks