---
# tasks file for encryption
- name: Generate an encryption key
  shell: export ENCRYPTION_KEY=$(head -c 32 /dev/urandom | base64)
  register: ENCRYPTION_KEY

- name: Create the encryption-config.yaml encryption config file
  shell: envsubst < encryption-config.yaml > encryption-config.yaml