---
# tasks file for encryption
- name: Generate an encryption key
  shell: export ENCRYPTION_KEY=$(head -c 32 /dev/urandom | base64)
  register: ENCRYPTION_KEY

- name: Create the encryption-config.yaml encryption config file
  shell: envsubst < "{{ role_path }}/files/encryption-config.yaml" > encryption-config.yaml

- name: Copy the encryption config to each controller instance
  shell: "scp -o StrictHostKeyChecking=no -p {{ item.1 }} {{ ansible_user }}@{{ item.0 }}:~"
  vars:
    files:
      - "encryption-config.yaml"
  loop: "{{ groups['controller'] | product(files) | list }}" 