---
# handlers file for compute-resources
- name: restart sshd
  become: yes
  block:
  - name: Disable ssh socket
    systemd:
      name: sshd.socket
      enabled: no
      state: stopped
    register: service_disabled
  - name: Reload the systemd daemon
    systemd:
      daemon_reload: yes
    when: service_disabled.changed
  - name: Stop ssh
    service:
      name: ssh
      state: stop
  - name: Start ssh
    service:
      name: ssh
      state: start
    