---
- name: Ensure certificate directory structure exists
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  with_items:
    - "{{ ca_dir }}"
    - "{{ certs_dir }}"
    - "{{ conf_dir }}"

- name: Generate CA private key
  community.crypto.openssl_privatekey:
    path: "{{ ca_key }}"
    size: 4096
    state: present
    type: RSA

- name: Copy CA conf file
  copy:
    src: "common.conf"
    dest: "{{ common_conf }}"
    force: no

- name: Generate self-signed CA certificate
  command: "openssl req -x509 -new -sha512 -noenc -key {{ ca_key }} -config {{ common_conf }} -days 3653 -out {{ ca_cert }}"

- name: generate admin certificate conf
  template:
    src: "admin.j2"
    dest: "{{ conf_dir }}/{{ item }}.conf"
  with_items:
    - "{{ groups['admin-machine'] }}"

- name: Generate node certificate conf
  template:
    src: "node.j2"
    dest: "{{ conf_dir }}/{{ item }}.conf"
  with_items:
    - "{{ groups['worker'] }}"

- name: Generate cert config file for kube components
  template:
    src: "kube.j2"
    dest: "{{ conf_dir }}/kube.conf"

- name: Generate combined config file
  assemble:
    src: "{{ conf_dir }}"
    dest: "{{ ca_conf }}"
    mode: '0644'

- name: Create client and server private keys
  openssl_privatekey:
    path: "{{ certs_dir }}/{{ item }}.key"
  with_items:
    - "{{ groups['admin-machine'] }}"
    - "{{ groups['worker'] }}"
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy
    - service-accounts

- name: Generate client and server certificate signing requests
  command: "openssl req -new -key {{ certs_dir }}/{{ item }}.key -sha256 \\
            -config {{ ca_conf }} -section {{ item }} \\
            -out {{ certs_dir }}/{{ item }}.csr"
  with_items:
    - "{{ groups['admin-machine'] }}"
    - "{{ groups['worker'] }}"
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy
    - service-accounts

- name: Sign the client and server certificates
  command: "openssl x509 -req -days 3653 -in {{ certs_dir }}/{{ item }}.csr \\
            -copy_extensions copyall -sha256 -CA {{ ca_dir }}/ca.crt \\
            -CAkey {{ ca_dir }}/ca.key -CAcreateserial \\
            -out {{ certs_dir }}/{{ item }}.crt"
  with_items:
    - "{{ groups['admin-machine'] }}"
    - "{{ groups['worker'] }}"
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy
    - service-accounts

- name: Distribute worker certs (key) to the correct worker node
  shell: "scp -o StrictHostKeyChecking=no -p {{ certs_dir}}/{{ item }}.* {{ ansible_user }}@{{ item }}:~/"
  # become: true
  loop: "{{ groups['worker'] }}"

- name: Move certs to correct location on worker
  shell: "mv ~{{ ansible_user }}/{{ item }}.* {{ kubelet_path }}"
  become: true
  loop: "{{ groups['worker'] }}"
  delegate_to: "{{ item }}"

- name: Distribute server certs to master nodes
  shell: "scp -o StrictHostKeyChecking=no -p {{ item.1 }} {{ ansible_user }}@{{ item.0 }}:~"
  vars:
    files:
    - "{{ ca_dir }}/ca.crt"
    - "{{ ca_dir }}/ca.key"
    - "{{ certs_dir }}/kube-apiserver.crt"
    - "{{ certs_dir }}/kube-apiserver.key"
    - "{{ certs_dir }}/service-accounts.crt"
    - "{{ certs_dir }}/service-accounts.key"
  loop: "{{ groups['controller'] | product(files) | list }}"

- name: Move certs to correct location on controller
  shell: "mv ~{{ ansible_user }}/{{ item.1 }} {{ kubelet_path }}/{{ item.1 }}"
  become: true
  vars:
    files:
    - "ca.crt"
    - "ca.key"
    - "kube-apiserver.crt"
    - "kube-apiserver.key"
    - "service-accounts.crt"
    - "service-accounts.key"
  loop: "{{ groups['controller'] | product(files) | list }}"
  delegate_to: "{{ item.0 }}"