---
- hosts: all
  gather_facts: true  # Gather facts once at the beginning of the playbook

- name: Setup admin machine
  hosts: "admin-machine"
  roles:
    - admin-machine
  tags: 
    - admin-machine

- name: Setup compute resources
  hosts: "kube-machines"
  roles:
    - compute-resources
  tags: 
    - compute-resources

- name: Setup certificates
  hosts: "admin-machine"
  roles:
    - certs
  tags: 
    - certs

- name: Kubelet Config files
  hosts: "admin-machine"
  roles:
    - kubeconfig
  tags: 
    - kubeconfig
