---
- hosts: all
  gather_facts: true  # Gather facts once at the beginning of the playbook

- name: Setup admin machine
  hosts: "admin-machine"
  roles:
    - admin-machine

- name: Setup compute resources
  hosts: "kube-machines"
  roles:
    - compute-resources

- name: Setup certificates
  hosts: localhost
  roles:
    - certs
