---
- name: Setup admin machine
  hosts: "admin-machine"
  gather_facts: true
  roles:
    - admin-machine

- name: Setup compute resources
  hosts: "kube-machines"
  gather_facts: true
  roles:
    - compute-resources
