all:
  children:
    controller:
      hosts:
        controller-0:
          ansible_host: controller-0
          ansible_user: ansible
    worker:
      hosts:
        worker-0:
          ansible_host: worker-0
          ansible_user: ansible
        worker-1:
          ansible_host: worker-1
          ansible_user: ansible
    admin-machine:
      hosts:
        admin-machine:
          ansible_host: admin-machine
          ansible_user: ansible
    kube-machines:
      children:
        controller:
        worker: