all:
  children:
    controller:
      hosts:
        controller-0:
          ansible_host: 192.168.1.117
          ansible_user: ansible
    worker:
      hosts:
        worker-0:
          ansible_host: 192.168.1.118
          ansible_user: ansible
        worker-1:
          ansible_host: 192.168.1.119
          ansible_user: ansible      
    admin-machine:
      hosts:
        admin-machine:
          ansible_host: 192.168.1.115
          ansible_user: ansible
    kube-machines:
      children:
        controller:
        worker: